version: "3.9"
services:
  api:
    build:
      context: .
    image: sprotsenko/cinema_sp_app:latest
    ports:
      - 25000:25000
    volumes:
      - ./docker_config.py:/app_code/config.py
    depends_on:
      pg_main_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  front:
    image: sprotsenko/cinema_sp_app_front:latest
    ports:
      - 80:2500
    depends_on:
      pg_main_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    image: sprotsenko/cinema_sp_app
    environment:
      FLASK_APP: 'run.py'
    volumes:
      - ./docker_config.py:/app_code/config.py
      - ./exchanger:/app_code/exchanger
    depends_on:
      pg_main_db:
        condition: service_healthy
    command: sh -c "python3 -m flask db upgrade"

  pg_main_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: main_db_user
      POSTGRES_PASSWORD: main_db_pass
      POSTGRES_DB: main_db
    volumes:
      - ./pg_main_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U main_db_user -d main_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
